---
title: "Task 01a"
format: html
---

# Making growth media for our experiments

## Making LB medium

The methods section does not provide a recipe for LB medium (this is so commonly used that it is considered "common knowledge" and doesn't require a citation, here) - so you will have to look up the recipe from a reputable source (here we will look at the Cold Spring Harbor colelction of protocols for the [LB liquid medium recipe](https://cshprotocols.cshlp.org/content/2006/1/pdb.rec8141.full?text_only=true)). 

> Reagent -	Amount to add
H<sub>2</sub>0 - 950 mL
Tryptone - 10 g
NaCl	- 10 g
Yeast extract	- 5 g
Combine the reagents and shake until the solutes have dissolved. Adjust the pH to 7.0 with 5 N NaOH (~0.2 mL). Adjust the final volume of the solution to 1 L with H<sub>2</sub>O. Sterilize by autoclaving for 20 min at 15 psi (1.05 kg/cm<sup>2</sub>) on liquid cycle.

::: { .callout-important }
Note that the recipe for LB as written is for making 1 L of LB. (Recipes for microbiological media are most commonly written for preparing 1 L of the medium.)

For our purposes, however, we only need 500 mL of media, so we will have to do some lab maths. 

It is good practice to only make up as much as you need of any reagent/medium: 

- This avoids cluttering the shelves with unneeded/unused bottles of reagents
- It avoids unnecessary waste, and is more sustainable
- It saves time and money in most instances
:::

::: { .callout-todo }
Your first task, therefore, is to calculate how much of each of the three components (tryptone, NaCl, and yeast extract) is necessary to make 500 mL of LB medium. Use these calculations to answer the questions in the quiz on MyPlace. 
:::

::: { .callout-tip title="Click here for hints on how to approach this calculation" collapse="true"}
As you develop your skills at lab maths, you will likely develop preferred methods of working. For most of these calculations, there is more than one method that will work to find the correct answer. 

You may find that you prefer to set up ratios, or to always use c<sub>1</sub>v<sub>1</sub> = c<sub>2</sub>v<sub>2</sub> to solve equations. (The precise method that you use is less important than arriving at the correct answer!)

However, one common theme for all methods, is that you must pay attention to the units! Using the wrong units can result in your answer being wrong by several orders of magnitude. 

Here, your first step might be to convert from mL to L (or vice versa) so that your volumes (500 mL of LB desired; 1 L as per the recipe) are expressed using the same units. 
:::

## Making M9 minimal medium

Similarly, the methods section does not provide a recipe for M9 medium - so you will again have to look up the recipe from a reputable source (here we will look at the Cold Spring Harbor colelction of protocols for the [5X M9 salts](https://cshprotocols.cshlp.org/content/2006/1/pdb.rec614)). 

### Making 5X M9 salts

You will make up the 5X M9 salts according to the recipe, but this then must be supplemented with the necessary ingredients to support bacterial growth. 

::: { .callout-question }

:::::{.question}
You have prepared 5X M9 salts. How should you dilute these to make 500 mL of 1X M9?

::::{.choices}

:::{.choice}
100 mL of the 5X M9 salts + 500 mL of water
:::  

:::{.choice .correct-choice}
100 mL of the 5X M9 salts + 400 mL of water
:::

:::{.choice}
500 mL of the 5X M9 salts + 100 mL of water  
:::

:::{.choice}
400 mL of the 5X M9 salts + 100 mL of water   
:::

:::{.button-clear title="Clear answer" button-class="btn btn-xs"}
:::

::::
:::::

::::{.btn-group}
:::{.button-hint title="Show hint" button-class="btn btn-xs"}
The 5X salt solution is 5 times more concentrated than a 1X solution...
:::

:::{.button-answer title="Show Answer" button-class="btn btn-xs"}
Your total final volume should be 500 mL. 1/5th of it should be the 5X M9 salts (to give a final concentration of 1X.) The remainder of the volume should be made up by water (400 mL).
:::
::::

:::


::: { .callout-important }
Microbial growth media must contain all of the elements required to support the growth of the microorganism in question. For rich media (like LB), heterogenous mixtures such as tryptone and yeast extract provide the bacteria with sources of carbon, nitrogen, and a range of different vitamins etc. 

However, to conduct more controlled experiments, we often grow bacteria in defined minimal media, where the composition of the growth medium is precisely known and controlled. 

Here, we have provided a range of salts (in the 5X M9 solution); however, the bacteria will also require nutrients (carbon and nitrogen). These are usually prepared separately, sterilised, and then added to the medium. (This prevents them from precipitating in the autoclave.)
:::

### Making the supplements required for growing our strains in M9 minimal medium

The supplements to the M9 medium are described in the methods section of the Mettler *et al.* paper: "0.2% glucose, 1 mM MgSO<sub>4</sub>, 2.5 μg ml<sup>−1</sup> ferric ammonium citrate, 2 μg ml<sup>−1</sup> thiamine, 0.02% ammonium molybdate, 12.5 μg ml<sup>−1</sup> nicotinic acid, and 0.1 mM CaCl<sub>2</sub>"

#### 0.2% glucose

You will need to add glucose (a carbon source) to your M9 medium so that it can support bacterial growth. The glucose must be prepared separately and filter-sterilised (molecules like sugars will undergo the [Maillard reaction](https://en.wikipedia.org/wiki/Maillard_reaction) if autoclaved.)

You must therefore prepare a more concentrated **stock solution** that can then be diluted to a final concentration of 0.2% in your culture medium. 

::: { .callout-tip }
In principle, a stock solution such as this glucose stock can be prepared to almost any concentration (subject to certain physicochemical limitations - the molecule in question must be soluble at that concentration). 

In practice, it is sensible to make the stock at a concentration that is convenient for us (both mathematically and practically in terms of pipetting). This most often means that we make stock solutions that are 100X or 1000X more concentrated than our final desired working concentration.
:::

#### 1 mM MgSO<sub>4</sub>

#### 2.5 μg ml<sup>−1</sup> ferric ammonium citrate

#### 2 μg ml<sup>−1</sup> thiamine

#### 0.02% ammonium molybdate

#### 12.5 μg ml<sup>−1</sup> nicotinic acid

#### 0.1 mM CaCl<sub>2</sub>



## Making MOPS minimal medium

You can find the recipe for making MOPS minimal medium in the reference provided (the original publication of this growth medium), or [online here](https://www.genome.wisc.edu/resources/protocols/mopsminimal.htm). 

This is a rather complicated medium to make up, so many researchers prefer to buy pre-made MOPS medium! 

Once you have made (or purchased) the 10X MOPS medium salts, you will want to make up a working stock of your medium (1X), which should be supplemented with arabinose and Casamino Acids as indicated in our methods. 

